# Generated by Django 4.2.15 on 2024-09-02 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="home_contact", old_name="Email", new_name="email",
        ),
        migrations.RenameField(
            model_name="home_contact", old_name="Name", new_name="name",
        ),
    ]
