# Generated by Django 4.2.15 on 2024-09-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_rename_email_home_contact_email_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="home_contact", new_name="contact_details",),
    ]
