# Generated by Django 4.2.15 on 2024-09-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_rename_home_contact_contact_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=30)),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("confirm_password", models.CharField(max_length=20)),
            ],
        ),
    ]
