# Generated by Django 4.2.15 on 2024-09-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_register"),
    ]

    operations = [
        migrations.CreateModel(
            name="personal_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("height", models.CharField(max_length=30)),
                ("weight", models.CharField(max_length=30)),
                ("age", models.CharField(max_length=30)),
                ("nationality", models.CharField(max_length=30)),
                ("sports", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="register",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="register",
            name="username",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
