# Generated by Django 4.2.15 on 2024-09-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_personal_info_competition_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="personal_info", name="sports",),
    ]
