# Generated by Django 4.2.15 on 2024-09-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_remove_personal_info_sports"),
    ]

    operations = [
        migrations.CreateModel(
            name="cardio_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resting_heart_rate", models.CharField(max_length=30)),
                ("max_heart_rate", models.CharField(max_length=30)),
                ("blood_pressure", models.CharField(max_length=30)),
                ("vo2_max", models.CharField(max_length=30)),
                ("hrv", models.CharField(max_length=30)),
                ("recovery_time", models.CharField(max_length=30)),
                ("cardiacOutput", models.CharField(max_length=30)),
                ("ldlCholesterol", models.CharField(max_length=30)),
                ("hdlCholesterol", models.CharField(max_length=30)),
                ("triglycerides", models.CharField(max_length=30)),
                ("fastingBloodSugar", models.CharField(max_length=30)),
                ("postprandialBloodSugar", models.CharField(max_length=30)),
                ("familyHistory", models.CharField(max_length=30)),
                ("cardiacEvents", models.CharField(max_length=30)),
                (
                    "blood_sugar_issues",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=3,
                    ),
                ),
                (
                    "blood_sugar_condition",
                    models.CharField(
                        blank=True,
                        help_text="Specify the condition if blood sugar issues are present.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "family_history",
                    models.CharField(
                        choices=[
                            ("No Known Family History", "No Known Family History"),
                            ("Single Case in Family", "Single Case in Family"),
                            ("Multiple Cases in Family", "Multiple Cases in Family"),
                            (
                                "Early Onset Cardiovascular Disease",
                                "Early Onset Cardiovascular Disease",
                            ),
                            (
                                "Genetic Cardiovascular Disorders",
                                "Genetic Cardiovascular Disorders",
                            ),
                        ],
                        default="No Known Family History",
                        max_length=50,
                    ),
                ),
                (
                    "cardiac_events",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Arrhythmias", "Arrhythmias"),
                            (
                                "Myocardial Infarction (Heart Attack)",
                                "Myocardial Infarction (Heart Attack)",
                            ),
                            ("Angina Pectoris", "Angina Pectoris"),
                            ("No Events", "No Events"),
                            (
                                "Congestive Heart Failure (CHF)",
                                "Congestive Heart Failure (CHF)",
                            ),
                            ("Stroke", "Stroke"),
                            (
                                "Coronary Artery Disease (CAD)",
                                "Coronary Artery Disease (CAD)",
                            ),
                            ("Cardiomyopathy", "Cardiomyopathy"),
                        ],
                        help_text="Select any previous cardiac events you have experienced.",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
