# Generated by Django 4.2.15 on 2024-09-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0009_remove_cardio_data_blood_sugar_issues_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardio_data",
            name="bloodSugarIssues",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No")],
                default="no",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cardio_data",
            name="cardiac_events",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Arrhythmias", "Arrhythmias"),
                    (
                        "Myocardial Infarction (Heart Attack)",
                        "Myocardial Infarction (Heart Attack)",
                    ),
                    ("Angina Pectoris", "Angina Pectoris"),
                    ("No Events", "No Events"),
                    (
                        "Congestive Heart Failure (CHF)",
                        "Congestive Heart Failure (CHF)",
                    ),
                    ("Stroke", "Stroke"),
                    ("Coronary Artery Disease (CAD)", "Coronary Artery Disease (CAD)"),
                    ("Cardiomyopathy", "Cardiomyopathy"),
                ],
                help_text="Select any previous cardiac events you have experienced.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cardio_data",
            name="family_history",
            field=models.CharField(
                blank=True,
                choices=[
                    ("No Known Family History", "No Known Family History"),
                    ("Single Case in Family", "Single Case in Family"),
                    ("Multiple Cases in Family", "Multiple Cases in Family"),
                    (
                        "Early Onset Cardiovascular Disease",
                        "Early Onset Cardiovascular Disease",
                    ),
                    (
                        "Genetic Cardiovascular Disorders",
                        "Genetic Cardiovascular Disorders",
                    ),
                ],
                default="No Known Family History",
                max_length=50,
                null=True,
            ),
        ),
    ]
