# Generated by Django 4.2.15 on 2024-09-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0014_cardiodata_contactdetails_personalinfo_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="cardiodata", name="report",),
        migrations.RemoveField(model_name="metric", name="report",),
        migrations.RemoveField(model_name="personalinfo", name="report",),
        migrations.DeleteModel(name="report",),
    ]
