# Generated by Django 4.2.15 on 2024-09-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0015_remove_cardiodata_report_remove_metric_report_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalinfo", old_name="age", new_name="DOB",
        ),
    ]
