# Generated by Django 4.2.15 on 2024-09-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0019_personalinfo_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="personalinfo", name="age",),
        migrations.RemoveField(model_name="personalinfo", name="gender",),
        migrations.RemoveField(model_name="personalinfo", name="user",),
        migrations.AddField(
            model_name="cardiodata",
            name="age",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="cardiodata",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="other",
                max_length=10,
            ),
        ),
    ]
